apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-application-controller-n8n-manager-binding
subjects:
- kind: ServiceAccount
  name: example-argocd-argocd-application-controller # The SA used by Argo CD
  namespace: argocd # Namespace of the SA
roleRef:
  kind: ClusterRole
  name: argocd-application-controller-n8n-manager # The ClusterRole created above
  apiGroup: rbac.authorization.k8s.io 